name: Node Image to ACR 

on:
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: cicdpipeline.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - run:
         docker build -t nodejs-docker "/home/runner/work/Common/Common/src"
#          docker tag .azurecr.io/$DOCKER_IMAGE
#          docker push $ACR_NAME.azurecr.io/$DOCKER_IMAGE
